### ISSUE TITLE
Feature Request: 12 hour time

### ISSUE THREAD

**Issue by KingdaToro** [virtualmatador/clock#1]
I would like the ability to display 12 hour time with AM/PM. I suggest making it toggleable in the configuration file, with "format 12" for 12-hour or "format 24" for 24-hour.

**Comment by virtualmatador** [comment]
Thanks for creating the issue. Implemented in version 2.3.0 with a slightly different configuration.
To show time in 12 hour format
`24-hour false`
Additionally hiding seconds is allowed in this version:
`seconds false`

**Comment by virtualmatador** [comment]
Thanks for creating the issue. Implemented in version 2.3.0 with a slightly different configuration.
To show time in 12 hour format
`24-hour false`
Additionally hiding seconds is allowed in this version:
`seconds false`
