### ISSUE TITLE
Feature request: Remove leading zeros

### ISSUE THREAD

**Issue by KingdaToro** [virtualmatador/clock#10]
It would be nice to have an option to remove leading zeros from the hour, month, and day. For example, displaying 4:01:09 PM 8/7/2024 instead of the current 04:01:09 PM 08/07/2024. In 24-hour mode, a single zero could be shown for the hour between midnight and 1:00. This would also have the beneficial side effect of varying the length of the display, causing it to shift horizontally to remain centered. This will help reduce burn-in on OLED displays.

**Comment by virtualmatador** [comment]
padding for individual fields can be configured by `pad-<name of the field> false`. Supported fields are  hour, minute, second, year, month, and day.
Version 2.6.0
