### ISSUE TITLE
2.3.0 requires newer GLIBCXX version than is available on Raspberry Pi

### ISSUE THREAD

**Issue by KingdaToro** [virtualmatador/clock#3]
I upgraded Clock to 2.3.0, and when attempting to run it from the command line on a Raspberry Pi, I get this error: 

`clock: /lib/aarch64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.32' not found (required by clock)`

The newest GLIBCXX version installed on Raspberry Pi OS Bookworm (the latest) is 3.4.30. There does not seem to be an easy way to update it.

**Comment by virtualmatador** [comment]
For now, building from source seems to be the only solution to run on systems with older GLIBCXX. I've added build instructions to README file.
I am also trying to fix the cross compile error on github actions, but seems to be a difficult job.
When github actions start to support arm64 runners, I will add workflow files to build for arm64.

**Comment by KingdaToro** [comment]
Built successfully! Feel free to replace the current Raspberry Pi release with [the package I built](https://kingdatoro.servegame.com/clock-aarch64.deb), which was done on a Raspberry Pi 5 running the latest Raspberry Pi OS Bookworm. I would be happy to do this for any future releases as well. Note: It's built from the dev branch, if you'd rather have one built from the main branch, just let me know!

**Comment by virtualmatador** [comment]
Glad your problem is solved. The artifacts on https://www.shaidin.com/clock are auto generated and will be overwritten if replaced manually. I will keep this issue open so others can find and download your build.
I suggest building from main branch.
Thanks.

**Comment by KingdaToro** [comment]
> Glad your problem is solved. The artifacts on https://www.shaidin.com/clock are auto generated and will be overwritten if replaced manually. I will keep this issue open so others can find and download your build. I suggest building from main branch. Thanks.

Appreciate it. I've updated it with a package built from main branch right after 2.3.1 was merged.

**Comment by virtualmatador** [comment]
Closing this issue, will revisit when arm64 runners come to github.
